import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@/app/contexts/UserContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ASA Philippines Mockup",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en">
        <head>
          <script src="https://kit.fontawesome.com/53aeb2e88e.js" crossOrigin="anonymous" async/>
        </head>
        <body className={inter.className}>
          <UserProvider>{children}</UserProvider>
        </body>
      </html>
    </>
    
  );
}
