import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ASA Philippines Mockup",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <head>
      <script src="https://kit.fontawesome.com/53aeb2e88e.js" crossOrigin="anonymous"></script>
      </head>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </>
    
  );
}
